<?php

declare(strict_types=1);

namespace SilenZ\Beeline\Cache;

use RuntimeException;
use SilenZ\Beeline\Compiler;
use UnitEnum;

use function array_is_list;
use function bin2hex;
use function file_put_contents;
use function function_exists;
use function hash;
use function implode;
use function is_array;
use function is_dir;
use function is_file;
use function mkdir;
use function opcache_invalidate;
use function random_bytes;
use function rename;
use function rtrim;
use function sprintf;
use function unlink;
use function var_export;

/**
 * Stores compiled routes as PHP files that are loaded with a plain `require`, and therefore served
 * from OPcache in production.
 *
 * Each key maps to its own file in the directory: `routecache_{hash of the key}.php`, or plain
 * `routecache.php` for a `null` key — a {@see \SilenZ\Beeline\RouteTable} declared without one, which
 * still caches rather than being treated as uncacheable, just under this one shared default file.
 *
 * A file returns the compiled structure unchanged, one line per table entry with a short comment
 * above each table, so it stays small and still readable.
 *
 * @psalm-import-type CompiledRoutes from Compiler
 */
final class FileCache implements RouteCache
{
    /** The tables of the compiled routes, in file order, each with the comment written above it. */
    private const array TABLES = [
        'static' => 'full path => route id(s), for routes without parameters',
        'edges' => 'node => static segment => child node (node 0 is the root)',
        'param' => 'node => child node of its {param} edge',
        'catch' => 'node => [needs a non-empty rest ({name+}), ...route ids of its catch-all edge]',
        'routes' => 'node => route id(s) ending there',
        'routeMetadata' => 'route id => metadata',
        'paramNames' => 'route id => parameter names, in capture order',
    ];

    private readonly string $directory;

    /** @var array<string, string> key => file, so long-running processes build each name once */
    private array $files = [];

    /** The `null`-key file, kept apart from {@see $files} so it can never collide with a real key. */
    private ?string $defaultFile = null;

    public function __construct(string $directory)
    {
        $this->directory = rtrim($directory, characters: '/\\');
    }

    public function get(?string $key): ?array
    {
        $file = $this->file($key);
        if (!is_file($file)) {
            return null;
        }

        /** @var mixed $compiled */
        $compiled = require $file;

        return is_array($compiled) ? $compiled : null;
    }

    /**
     * Writes atomically (temporary file + rename), so concurrent requests never `require` a partial file.
     */
    public function set(?string $key, array $compiled): void
    {
        $directory = $this->directory;
        // @mago-expect lint:no-error-control-operator - the failure is handled below; we don't need the warning text
        if (!is_dir($directory) && !@mkdir($directory, permissions: 0o777, recursive: true) && !is_dir($directory)) {
            throw new RuntimeException(sprintf('Unable to create route cache directory "%s".', $directory));
        }

        $file = $this->file($key);
        $temporary = $file . '.' . bin2hex(random_bytes(6)) . '.tmp';
        // @mago-expect lint:no-error-control-operator - the failure is handled below; we don't need the warning text
        if (@file_put_contents($temporary, self::export($compiled)) === false) {
            throw new RuntimeException(sprintf('Unable to write route cache file "%s".', $temporary));
        }

        try {
            // @mago-expect lint:no-error-control-operator - the failure is handled below; we don't need the warning text
            if (@rename($temporary, $file) === false) {
                throw new RuntimeException(sprintf('Unable to move route cache file into "%s".', $file));
            }
        } finally {
            if (is_file($temporary)) {
                unlink($temporary);
            }
        }

        if (function_exists('opcache_invalidate')) {
            opcache_invalidate($file, force: true);
        }
    }

    /**
     * The file a key is stored in, e.g. "routes-v2" => "<directory>/routecache_1b3c9a44.php", or, for
     * `null`, the one shared "<directory>/routecache.php".
     */
    public function file(?string $key): string
    {
        if ($key === null) {
            return $this->defaultFile ??= $this->directory . '/routecache.php';
        }

        return $this->files[$key] ??= $this->directory . '/routecache_' . hash('xxh32', $key) . '.php';
    }

    /**
     * @param CompiledRoutes $compiled
     */
    private static function export(array $compiled): string
    {
        $lines = [
            '<?php',
            '',
            '// Generated by silenz/segmatch. Do not edit.',
            '',
            'declare(strict_types=1);',
            '',
            'return [',
            "    'version' => " . var_export($compiled['version'], return: true) . ',',
            '',
            '    // metadata of the route table as a whole, not of any one route',
            "    'metadata' => " . self::inline($compiled['metadata']) . ',',
        ];

        foreach (self::TABLES as $name => $description) {
            $table = $compiled[$name];
            $lines[] = '';
            $lines[] = '    // ' . $description;
            if ($table === []) {
                $lines[] = '    ' . var_export($name, return: true) . ' => [],';
                continue;
            }

            $lines[] = '    ' . var_export($name, return: true) . ' => [';
            $list = array_is_list($table);
            foreach ($table as $key => $value) {
                $prefix = $list ? '/* ' . $key . ' */ ' : var_export($key, return: true) . ' => ';
                $lines[] = '        ' . $prefix . self::inline($value) . ',';
            }
            $lines[] = '    ],';
        }

        $lines[] = '];';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private static function inline(mixed $value): string
    {
        if (!is_array($value)) {
            return self::scalar($value);
        }

        $list = array_is_list($value);
        $items = [];
        foreach ($value as $key => $item) {
            $items[] = ($list ? '' : var_export($key, return: true) . ' => ') . self::inline($item);
        }

        return '[' . implode(', ', $items) . ']';
    }

    private static function scalar(mixed $value): string
    {
        if ($value instanceof UnitEnum) {
            return '\\' . $value::class . '::' . $value->name;
        }

        return var_export($value, return: true);
    }
}
